### ISSUE TITLE
The type initializer for 'Gdip' threw an exception.

### ISSUE THREAD

**Issue by SpringHgui** [Shane32/QRCoder#389]
## Type of issue
[ x] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Behavior

System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
   at System.Drawing.LibraryResolver.EnsureRegistered()
   at System.Drawing.SafeNativeMethods.Gdip.PlatformInitialize()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, IntPtr scan0, IntPtr& bitmap)

 https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

**Comment by jtammaro** [comment]
+1

**Comment by uziruk** [comment]
+1, I believe this has to do with microsoft droping system.drawing support on non windows oses

**Comment by JoseAFerrer** [comment]
+1, but I thought it had something to do with my system being an Apple M1. I'll keep working on it and let you know if I manage to solve it.

**Comment by namespacedevbox** [comment]
temporary solution, create runtimeconfig.template.json
```
{
   "configProperties": {
      "System.Drawing.EnableUnixSupport": true
   }
}
```
works on linux

**Comment by tkggusraqk** [comment]
> 
The aarch64 schema test is invalid
![error](https://user-images.githubusercontent.com/5164663/210604520-c729c8af-c980-4779-bbe3-e8a6143deff9.png)

**Comment by Shane32** [comment]
Plan is to support ImageSharp and/or other libraries in v2.  For now some basic renderers are available such as the PNG and SVG renderers.
